# PHP
php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www/html
  entrypoint:
    - php-fpm
  links:
    - mysql

# POSTRESQL   
# postgres:
#   image: postgres
#   container_name: postgres_database
#   restart: always
#   volumes:
#     - ./data/postgres:/var/lib/postgresql/data
#   ports:
#     - 5432:5432
#   environment:
#     POSTGRES_DB: dev_app
#     POSTGRES_USER: dev_app
#     POSTGRES_PASSWORD: 1234

# MYQSL
mysql:
  image: mysql
  container_name: mysql_database
  restart: always
  ports:
    - 33060:3306
  environment:
    MYSQL_DATABASE: dev_app
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_USER: dev_app
    MYSQL_PASSWORD: 1234

# NGINX
nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80

swagger:
  image: swaggerapi/swagger-editor
  container_name: swagger
  # environment:
  #   - "swagger_json": "/mnt/swagger.json"
  volumes:
    - ./api/swagger/:/mnt/
  links:
    - php
  ports:
    - 8090:8080

